from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

TOKEN = "##STATIC_ASSETS_PLACEHOLDER##"
STATIC_ASSETS_PATTERN = re.compile(
    r'_static_assets = \[.*?\]\n_static_assets = \{"/" \+ sa: Path\(__file__\)\.parent / sa for sa in _static_assets\}',
    re.DOTALL,
)


def infer_static_assets(app_path: Path) -> list[str]:
    """Infer static asset folders generated by Quarto beside app.py."""
    parent = app_path.parent
    assets = sorted(
        p.name
        for p in parent.iterdir()
        if p.is_dir() and (p.name.endswith("_files") or p.name == "www")
    )
    return assets


def render_static_assets_block(assets: list[str]) -> str:
    lines = ["_static_assets = {"]
    lines.extend(
        f'    "/{asset}": Path(__file__).parent / "{asset}",' for asset in assets
    )
    lines.append("}")
    return "\n".join(lines)


def patch_app_file(app_path: Path) -> tuple[str, list[str]]:
    if not app_path.exists():
        return "missing", []

    contents = app_path.read_text(encoding="utf-8")
    assets = infer_static_assets(app_path)
    expected_block = render_static_assets_block(assets)

    if expected_block in contents:
        return "current", assets

    if TOKEN in contents:
        contents = contents.replace(TOKEN, json.dumps(assets))
    elif STATIC_ASSETS_PATTERN.search(contents):
        contents = STATIC_ASSETS_PATTERN.sub(expected_block, contents)
    else:
        return "unpatched", []

    app_path.write_text(contents, encoding="utf-8")
    return "patched", assets


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Patch unresolved Quarto static assets placeholders in generated app.py files."
    )
    parser.add_argument(
        "--app",
        dest="app_paths",
        action="append",
        default=[],
        help="Path to a generated app.py file. Can be provided multiple times.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    app_paths = args.app_paths or ["src/healthcare_accessibility/app.py"]

    patched_any = False
    for app_str in app_paths:
        app_path = Path(app_str)
        status, assets = patch_app_file(app_path)
        if status == "missing":
            print(f"[skip] app file not found: {app_path}")
            continue
        if status == "patched":
            patched_any = True
            print(f"[patched] {app_path} -> static assets: {assets}")
        elif status == "current":
            print(f"[ok] static assets already configured: {app_path} -> {assets}")
        else:
            print(f"[ok] no patchable static assets block found: {app_path}")

    return 0 if patched_any or app_paths else 1


if __name__ == "__main__":
    raise SystemExit(main())
